### ISSUE TITLE
不仅仅是 README 和 wiki

### ISSUE THREAD

**Issue by dd1994** [summerblue/github-toc#2]
比如这样的 [CONTRIBUTING.md](https://github.com/rubyworks/facets/blob/master/CONTRIBUTING.md)

总之，在 github 的任何 repo 里，有 markdown 文件存在的地方，都需要你的 toc 来救援...

**Comment by summerblue** [comment]
![image](https://cloud.githubusercontent.com/assets/324764/7287182/df19120a-e984-11e4-9ada-235d93f00db1.png)

有呀.

**Comment by dd1994** [comment]
好吧，好像是我电脑出问题了，昨天还每没有的，今天早上就有了，so sorry...

**Comment by summerblue** [comment]
@dd1994 :smile: 没事.
